// src/common/constant/ErrorCodes.ts
export const ErrorCodes = {
  // Common
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  BAD_REQUEST: "BAD_REQUEST",
  NOT_FOUND: "NOT_FOUND",

  // Auth
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  INVALID_TOKEN: "INVALID_TOKEN",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",

  // User
  USER_NOT_FOUND: "USER_NOT_FOUND",
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",

  // OTP
  OTP_EXPIRED: "OTP_EXPIRED",
  OTP_INVALID: "OTP_INVALID",

  // Database
  DATABASE_ERROR: "DATABASE_ERROR",
  DUPLICATE_RECORD: "DUPLICATE_RECORD",

  // Redis
  REDIS_ERROR: "REDIS_ERROR",

  // Prisma
  PRISMA_ERROR: "PRISMA_ERROR",
} as const;